title: default-project-template
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps
  - title: Introduction
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 24 
      passing_score: 24
  - title: Next      