---
title: Durham Quiz
hero_image: images/banner.png
description:
meta_title:
meta_description:
version: 4
listed: false
copyedit: false
last_tested: "2023-06-19"
steps:
  - title: Introduction
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: What next?